# Generated by Django 4.0.5 on 2022-06-18 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handbook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='handbook',
            name='identifier',
            field=models.UUIDField(default=1, verbose_name='Идентификатор'),
            preserve_default=False,
        ),
    ]
