# Generated by Django 4.0.5 on 2022-06-18 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handbook', '0002_handbook_identifier'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='handbook',
            unique_together={('identifier', 'version')},
        ),
    ]
